url: 'https://astrolamusic.com'
baseurl: ''
title: 'Follow me on Spotify'

plugins:
  - jekyll-postcss

postcss:
  cache: false

exclude:
  - package.json
  - postcss.config.js
  - tailwind.config.js
  - package-lock.json
